### ISSUE TITLE
Azure AD connectivity

### ISSUE THREAD

**Issue by YvesCandel** [alexziskind1/nativescript-oauth#12]
Would it be possible to use this library for an Azure AD login only available to one specific AD Tenant?

Because currently the Office365 interface of this library offers no support to enter a specific tenant. If 'common' could be replaced with a specific Tenant ID, the login would already be restricted to company users. I've tried this manually but then the login stagnates on the actual login button, nothing seems to happen. Do only the Converged apps work with this library or does an Azure AD registered app work too? 

Any suggestions on how to integrate this into an enterprise employee-only app?

Thanks in advance

**Comment by alexziskind1** [comment]
Hi,

I haven't tested this with single tenant scenarios, but please take a look
at this article as it may shine some light on what can be done in Azure AD
application configuration to help you out:
https://docs.microsoft.com/en-us/azure/active-directory/active-directory-authentication-scenarios

Alex

On Jan 4, 2017, at 5:40 AM, Yves Candel <notifications@github.com> wrote:

Would it be possible to use this library for an Azure AD login only
available to one specific AD Tenant?

Because currently the Office365 interface of this library offers no support
to enter a specific tenant. If 'common' could be replaced with a specific
Tenant ID, the login would already be restricted to company users. I've
tried this manually but then the login stagnates on the actual login
button, nothing seems to happen. Do only the Converged apps work with this
library or does an Azure AD registered app work too?

Any suggestions on how to integrate this into an enterprise employee-only
app?

Thanks in advance

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/alexziskind1/nativescript-oauth/issues/12>, or mute the
thread
