### ISSUE TITLE
App turns out very big when including this module

### ISSUE THREAD

**Issue by Gerstalexej** [alexziskind1/nativescript-oauth#14]
The size of my app has increased to a staggering 250MB since including this module. How can that be?

![image](https://cloud.githubusercontent.com/assets/6694504/21805199/3ed0531e-d733-11e6-962f-84372f3347f8.png)

(the one I selected is nativescrit oauth)

**Comment by alexziskind1** [comment]
Since this plugin doesn't include anything in your project other than a
couple of small JavaScript files, I find it difficult to see why this could
happen.

Can you please provide the following?
What are you measuring? What's this graphic of? Do you have a sample
project? Are you including other libs?



On Jan 10, 2017, at 6:50 AM, Gerstalexej <notifications@github.com> wrote:

The size of my app has increased to a staggering 250MB since including this
module. How can that be?

[image: image]
<https://cloud.githubusercontent.com/assets/6694504/21805199/3ed0531e-d733-11e6-962f-84372f3347f8.png>

(the one I selected is nativescrit oauth)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/alexziskind1/nativescript-oauth/issues/14>, or mute the
thread

**Comment by Gerstalexej** [comment]
The following graphic is a list of all folders inside the node_modules folder in my project.

![image](https://cloud.githubusercontent.com/assets/6694504/21815304/66203424-d75c-11e6-82ed-dd7fd5cf2704.png)

It seems that this "demo-angular" might be the culprit? (I don't use angular in my app right now by the way)

Sorry for being so imprecise in my orignal post. The problem might be on my part too, I'm still a beginner at nativescript but your videos have helped me so far!

**Comment by alexziskind1** [comment]
Thanks for the extra info. It looks like the demo-angular project is the
heavy part.

When you add NativeScript-oauth to your project, the best way is to use
'npm install nativescript-oauth --save'
This way you won't get all the extra demo project code in there.

Hope this helps.

Alex

On Jan 10, 2017, at 11:46 AM, Gerstalexej <notifications@github.com> wrote:

The following graphic is a list of all folders inside the node_modules
folder in my project.

[image: image]
<https://cloud.githubusercontent.com/assets/6694504/21815304/66203424-d75c-11e6-82ed-dd7fd5cf2704.png>

It seems that this "demo-angular" might be the culprit? (I don't use
angular in my app right now by the way)

Sorry for being so imprecise in my orignal post. The problem might be on my
part too, I'm still a beginner at nativescript but your videos have helped
me so far!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/alexziskind1/nativescript-oauth/issues/14#issuecomment-271628643>,
or mute the thread

**Comment by Gerstalexej** [comment]
It seems like "demo-angular" ist still included, even if I use the --save flag.

During the building of the app "mergeF0F1F2DebugAssets" takes a huge amount of time, the file is probably in there.

Maybe there is some flag that makes the app be built NOT in debug mode. (I don't need these DebugAssets inside tha app)

**Comment by alexziskind1** [comment]
Looks like I didn't include demo-angular in the npmignore file and the demo might have been distributed with the package. I've published fix. Nice catch!
