### ISSUE TITLE
usage with custome oauth provider example?

### ISSUE THREAD

**Issue by mshanak** [alexziskind1/nativescript-oauth#18]
is there any tutorial or wiki of how to use this module with custom oauth provider ( like laravel passport) ?

**Comment by alexziskind1** [comment]
Hi Mahdi,

Currently there is no built in support for passport, but feel free to
contribute.

Alex

On Jan 20, 2017, at 4:01 PM, Mahdi <notifications@github.com> wrote:

is there any tutorial or wiki of how to use this module with costume oauth
provider ( like laravel passport) ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/alexziskind1/nativescript-oauth/issues/18>, or mute the
thread
