### ISSUE TITLE
Using this for a private identity server?

### ISSUE THREAD

**Issue by ctcoulter** [alexziskind1/nativescript-oauth#22]
Hey. I'm fairly new to the world of angular/typescript/nativescript. Is it possible to use this library to interact with a different type of server that supports OAuth? Specifically, I've got an IdentityServer4 instance stood up that i'd like to communicate with. I see you've got a generic "auth-helper.ts", but I only see initialization functions available for Google, Facebook and Microsoft.

Is this something I'd just need to roll my own version of, or am I just missing how to initialize it correctly with my own identity provider?

**Comment by alexziskind1** [comment]
Hi,

Yes for IS4, you'll need to create your own wrapper. This is something I'm
planning to work on, but not for a while. Your contributions would be
appreciated.


On Feb 10, 2017, at 9:26 PM, ctcoulter <notifications@github.com> wrote:

Hey. I'm fairly new to the world of angular/typescript/nativescript. Is it
possible to use this library to interact with a different type of server
that supports OAuth? Specifically, I've got an IdentityServer4 instance
stood up that i'd like to communicate with. I see you've got a generic
"auth-helper.ts", but I only see initialization functions available for
Google, Facebook and Microsoft.

Is this something I'd just need to roll my own version of, or am I just
missing how to initialize it correctly with my own identity provider?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/alexziskind1/nativescript-oauth/issues/22>, or mute the
thread

**Comment by Dashue** [comment]
Could definitely use this for a different provider as well.
Maybe just a quick writeup of how to add support for another provider would be quicker than implementation?

**Comment by Peperud** [comment]
In the OpenIdConnect/OAuth2 world, IdentityServer would the more general implementation, which probably can serve as a base for the rest of them.
