### ISSUE TITLE
Unknown URI Scheme in Android

### ISSUE THREAD

**Issue by ronakcshah** [alexziskind1/nativescript-oauth#24]
Using the library for custom ping server. Changes work well for iOS but run into this issue for android.

![err_android_uri](https://cloud.githubusercontent.com/assets/5214360/23001108/693321dc-f398-11e6-8f71-2772c273b81d.png)

**Comment by alexziskind1** [comment]
Could you please provide more info?

**Comment by ronakcshah** [comment]
nativescript@2.5.0
tns-ios@2.5.0
nativescript-oauth@1.2.1

Which files would you like to see?

**Comment by alexziskind1** [comment]
Please upgrade to nativescript-oauth 1.3.0 and try

**Comment by ronakcshah** [comment]
After upgrading to 1.3.0, iOS continuous to work but Android crashes upon opening of WebView. 

Attaching my sample code for 1.2.1 and 1.3.0. 

[app1.2.1.zip](https://github.com/alexziskind1/nativescript-oauth/files/779205/app1.2.1.zip)
[app1.3.zip](https://github.com/alexziskind1/nativescript-oauth/files/779204/app1.3.zip)

**Comment by alexziskind1** [comment]
It looks like you're not using the published npm package for nativescript-oauth, but instead you've created your own copy and trying to connect to Cisco. While what you've done is a good first step, I don't have access to a cisco environment to test this code.
Since you're digging into the code yourself and overriding a few things, then I will point you to the function that checks the return URL:
In the tns-oauth.ts file, there is a function called ```checkCodeIntercept```, where you should check for whatever string your cisco provider returns.
