### ISSUE TITLE
Unable to build plugin from root - error TS2307

### ISSUE THREAD

**Issue by jenga** [alexziskind1/nativescript-oauth#32]
First off - thanks for this plugin. I am using it in a {NS} app and it is working great with Facebook. I am trying to extend the plugin to use a separate private server for the code/token exchange (a la [satellizer](https://github.com/sahat/satellizer#-login-with-oauth-20)), but am having issues building the plugin as per the direction in the README.

After running `npm install` from the root directory, I run `tsc` and get the following list of errors:

```
index.ts(5,36): error TS2307: Cannot find module 'application'.
index.ts(6,24): error TS2307: Cannot find module 'utils/utils'.
index.ts(115,32): error TS2304: Cannot find name 'ErrorEvent'.
references.d.ts(1,1): error TS6053: File '/Users/j###/nativescript-oauth/demo/node_modules/tns-core-modules/tns-core-modules.es2016.d.ts' not found.
references.d.ts(3,1): error TS6053: File '/Users/j###/nativescript-oauth/demo/node_modules/tns-platform-declarations/ios.d.ts' not found.
references.d.ts(4,1): error TS6053: File '/Users/j###/nativescript-oauth/demo/node_modules/tns-platform-declarations/android.d.ts' not found.
tns-oauth-page-provider.ts(3,22): error TS2307: Cannot find module 'ui/page'.
tns-oauth-page-provider.ts(4,28): error TS2307: Cannot find module 'ui/layouts/grid-layout'.
tns-oauth-page-provider.ts(5,29): error TS2307: Cannot find module 'ui/layouts/stack-layout'.
tns-oauth-page-provider.ts(6,25): error TS2307: Cannot find module 'ui/web-view'.
tns-oauth-token-cache.ts(5,44): error TS2307: Cannot find module 'application-settings'.
tns-oauth-webview-helper.android.ts(3,25): error TS2307: Cannot find module 'ui/web-view'.
tns-oauth-webview-helper.android.ts(4,24): error TS2307: Cannot find module 'trace'.
tns-oauth-webview-helper.android.ts(6,44): error TS2304: Cannot find name 'android'.
tns-oauth-webview-helper.android.ts(14,23): error TS2339: Property '__native' does not exist on type 'Global'.
tns-oauth-webview-helper.android.ts(34,43): error TS2503: Cannot find namespace 'android'.
tns-oauth-webview-helper.android.ts(44,32): error TS2503: Cannot find namespace 'android'.
tns-oauth-webview-helper.android.ts(44,78): error TS2503: Cannot find namespace 'android'.
tns-oauth-webview-helper.android.ts(58,33): error TS2503: Cannot find namespace 'android'.
tns-oauth-webview-helper.android.ts(72,19): error TS2503: Cannot find namespace 'android'.
tns-oauth-webview-helper.d.ts(3,26): error TS2307: Cannot find module 'ui/web-view'.
tns-oauth-webview-helper.ios.ts(3,25): error TS2307: Cannot find module 'ui/web-view'.
tns-oauth-webview-helper.ios.ts(5,44): error TS2304: Cannot find name 'NSObject'.
tns-oauth-webview-helper.ios.ts(5,64): error TS2304: Cannot find name 'UIWebViewDelegate'.
tns-oauth-webview-helper.ios.ts(6,36): error TS2304: Cannot find name 'UIWebViewDelegate'.
tns-oauth-webview-helper.ios.ts(8,21): error TS2304: Cannot find name 'WeakRef'.
tns-oauth-webview-helper.ios.ts(17,71): error TS2304: Cannot find name 'WeakRef'.
tns-oauth-webview-helper.ios.ts(20,41): error TS2304: Cannot find name 'WeakRef'.
tns-oauth-webview-helper.ios.ts(28,69): error TS2304: Cannot find name 'UIWebView'.
tns-oauth-webview-helper.ios.ts(28,89): error TS2304: Cannot find name 'NSURLRequest'.
tns-oauth-webview-helper.ios.ts(32,41): error TS2304: Cannot find name 'UIWebView'.
tns-oauth-webview-helper.ios.ts(36,42): error TS2304: Cannot find name 'UIWebView'.
tns-oauth-webview-helper.ios.ts(41,49): error TS2304: Cannot find name 'UIWebView'.
tns-oauth-webview-helper.ios.ts(41,67): error TS2304: Cannot find name 'NSError'.
tns-oauth.ts(7,24): error TS2307: Cannot find module 'trace'.
tns-oauth.ts(8,30): error TS2307: Cannot find module 'ui/frame'.
tns-oauth.ts(9,27): error TS2307: Cannot find module 'platform'.
tns-oauth.ts(197,48): error TS2304: Cannot find name 'NSHTTPCookieStorage'.
tns-oauth.ts(199,25): error TS2304: Cannot find name 'NSHTTPCookie'.
tns-oauth.ts(199,41): error TS2304: Cannot find name 'NSHTTPCookie'.
tns-oauth.ts(202,21): error TS2304: Cannot find name 'NSHTTPCookieStorage'.
tns-oauth.ts(207,29): error TS2304: Cannot find name 'android'.
tns-oauth.ts(319,39): error TS2694: Namespace '"http"' has no exported member 'HttpResponse'.
tns-oauth.ts(357,83): error TS2694: Namespace '"http"' has no exported member 'HttpResponse'.
tns-oauth.ts(393,68): error TS2694: Namespace '"http"' has no exported member 'HttpResponse'.
tns-oauth.ts(395,13): error TS2345: Argument of type '{ url: any; method: any; headers: any; content: any; }' is not assignable to parameter of type 'RequestOptions'.
  Object literal may only specify known properties, and 'url' does not exist in type 'RequestOptions'.
```

Environment:
**OS:** Mac OSX 10.11.6
**Node:** 6.2.2
**Typescript:** 2.2.1
**tns:** 2.5.0
**npm:** 4.1.2

I am fairly new to typescript, so this might be something minor, but any help would be appreciated.

**Comment by alexziskind1** [comment]
Please go to the demo folder, run 'tns install' there, then go back out to
the root folder and run 'npm install'. Hopefully this workflow will be
improved a bit in the future.

On Mar 15, 2017, at 7:37 PM, Jordan Engbers <notifications@github.com>
wrote:

First off - thanks for this plugin. I am using it in a {NS} app and it is
working great with Facebook. I am trying to extend the plugin to use a
separate private server for the code/token exchange (a la satellizer
<https://github.com/sahat/satellizer#-login-with-oauth-20>), but am having
issues building the plugin as per the direction in the README.

After running npm install from the root directory, I run tsc and get the
following list of errors:

index.ts(5,36): error TS2307: Cannot find module 'application'.
index.ts(6,24): error TS2307: Cannot find module 'utils/utils'.
index.ts(115,32): error TS2304: Cannot find name 'ErrorEvent'.
references.d.ts(1,1): error TS6053: File
'/Users/j###/nativescript-oauth/demo/node_modules/tns-core-modules/tns-core-modules.es2016.d.ts'
not found.
references.d.ts(3,1): error TS6053: File
'/Users/j###/nativescript-oauth/demo/node_modules/tns-platform-declarations/ios.d.ts'
not found.
references.d.ts(4,1): error TS6053: File
'/Users/j###/nativescript-oauth/demo/node_modules/tns-platform-declarations/android.d.ts'
not found.
tns-oauth-page-provider.ts(3,22): error TS2307: Cannot find module 'ui/page'.
tns-oauth-page-provider.ts(4,28): error TS2307: Cannot find module
'ui/layouts/grid-layout'.
tns-oauth-page-provider.ts(5,29): error TS2307: Cannot find module
'ui/layouts/stack-layout'.
tns-oauth-page-provider.ts(6,25): error TS2307: Cannot find module
'ui/web-view'.
tns-oauth-token-cache.ts(5,44): error TS2307: Cannot find module
'application-settings'.
tns-oauth-webview-helper.android.ts(3,25): error TS2307: Cannot find
module 'ui/web-view'.
tns-oauth-webview-helper.android.ts(4,24): error TS2307: Cannot find
module 'trace'.
tns-oauth-webview-helper.android.ts(6,44): error TS2304: Cannot find
name 'android'.
tns-oauth-webview-helper.android.ts(14,23): error TS2339: Property
'__native' does not exist on type 'Global'.
tns-oauth-webview-helper.android.ts(34,43): error TS2503: Cannot find
namespace 'android'.
tns-oauth-webview-helper.android.ts(44,32): error TS2503: Cannot find
namespace 'android'.
tns-oauth-webview-helper.android.ts(44,78): error TS2503: Cannot find
namespace 'android'.
tns-oauth-webview-helper.android.ts(58,33): error TS2503: Cannot find
namespace 'android'.
tns-oauth-webview-helper.android.ts(72,19): error TS2503: Cannot find
namespace 'android'.
tns-oauth-webview-helper.d.ts(3,26): error TS2307: Cannot find module
'ui/web-view'.
tns-oauth-webview-helper.ios.ts(3,25): error TS2307: Cannot find
module 'ui/web-view'.
tns-oauth-webview-helper.ios.ts(5,44): error TS2304: Cannot find name
'NSObject'.
tns-oauth-webview-helper.ios.ts(5,64): error TS2304: Cannot find name
'UIWebViewDelegate'.
tns-oauth-webview-helper.ios.ts(6,36): error TS2304: Cannot find name
'UIWebViewDelegate'.
tns-oauth-webview-helper.ios.ts(8,21): error TS2304: Cannot find name 'WeakRef'.
tns-oauth-webview-helper.ios.ts(17,71): error TS2304: Cannot find name
'WeakRef'.
tns-oauth-webview-helper.ios.ts(20,41): error TS2304: Cannot find name
'WeakRef'.
tns-oauth-webview-helper.ios.ts(28,69): error TS2304: Cannot find name
'UIWebView'.
tns-oauth-webview-helper.ios.ts(28,89): error TS2304: Cannot find name
'NSURLRequest'.
tns-oauth-webview-helper.ios.ts(32,41): error TS2304: Cannot find name
'UIWebView'.
tns-oauth-webview-helper.ios.ts(36,42): error TS2304: Cannot find name
'UIWebView'.
tns-oauth-webview-helper.ios.ts(41,49): error TS2304: Cannot find name
'UIWebView'.
tns-oauth-webview-helper.ios.ts(41,67): error TS2304: Cannot find name
'NSError'.
tns-oauth.ts(7,24): error TS2307: Cannot find module 'trace'.
tns-oauth.ts(8,30): error TS2307: Cannot find module 'ui/frame'.
tns-oauth.ts(9,27): error TS2307: Cannot find module 'platform'.
tns-oauth.ts(197,48): error TS2304: Cannot find name 'NSHTTPCookieStorage'.
tns-oauth.ts(199,25): error TS2304: Cannot find name 'NSHTTPCookie'.
tns-oauth.ts(199,41): error TS2304: Cannot find name 'NSHTTPCookie'.
tns-oauth.ts(202,21): error TS2304: Cannot find name 'NSHTTPCookieStorage'.
tns-oauth.ts(207,29): error TS2304: Cannot find name 'android'.
tns-oauth.ts(319,39): error TS2694: Namespace '"http"' has no exported
member 'HttpResponse'.
tns-oauth.ts(357,83): error TS2694: Namespace '"http"' has no exported
member 'HttpResponse'.
tns-oauth.ts(393,68): error TS2694: Namespace '"http"' has no exported
member 'HttpResponse'.
tns-oauth.ts(395,13): error TS2345: Argument of type '{ url: any;
method: any; headers: any; content: any; }' is not assignable to
parameter of type 'RequestOptions'.
  Object literal may only specify known properties, and 'url' does not
exist in type 'RequestOptions'.

I am fairly new to typescript, so this might be something minor, but any
help would be appreciated.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/alexziskind1/nativescript-oauth/issues/32>, or mute the
thread

**Comment by jenga** [comment]
Thanks @alexziskind1 . I just figured that out and now see that it is mentioned in step 7 of the developer instructions.

If I can figure out how to improve that workflow, I will send a PR.
