### ISSUE TITLE
Calling js method shouldOverrideUrlLoading failed

### ISSUE THREAD

**Issue by witi83** [alexziskind1/nativescript-oauth#35]
Device: OnePlus 3T
Android: 7.1.1
nativescript-oauth: 1.3.0

```
04-11 21:58:59.659 18848 18848 W System.err: com.tns.NativeScriptException: 
04-11 21:58:59.659 18848 18848 W System.err: Calling js method shouldOverrideUrlLoading failed
04-11 21:58:59.659 18848 18848 W System.err: 
04-11 21:58:59.659 18848 18848 W System.err: TypeError: Parameter 'url' must be a string, not object
04-11 21:58:59.659 18848 18848 W System.err: File: "file:///data/data/org.nativescript.nativescriptapps/files/app/tns_modules/nativescript-oauth/node_modules/url/url.js, line: 112, column: 4
04-11 21:58:59.659 18848 18848 W System.err: 
04-11 21:58:59.659 18848 18848 W System.err: StackTrace: 
04-11 21:58:59.659 18848 18848 W System.err: 	Frame: function:'Url.parse', file:'file:///data/data/org.nativescript.nativescriptapps/files/app/tns_modules/nativescript-oauth/node_modules/url/url.js', line: 112, column: 11
04-11 21:58:59.659 18848 18848 W System.err: 	Frame: function:'urlParse', file:'file:///data/data/org.nativescript.nativescriptapps/files/app/tns_modules/nativescript-oauth/node_modules/url/url.js', line: 106, column: 5
04-11 21:58:59.659 18848 18848 W System.err: 	Frame: function:'checkCodeIntercept', file:'file:///data/data/org.nativescript.nativescriptapps/files/app/tns_modules/nativescript-oauth/tns-oauth.js', line: 81, column: 40
04-11 21:58:59.660 18848 18848 W System.err: 	Frame: function:'TnsOAuthWebViewHelper.shouldOverrideUrlLoading', file:'file:///data/data/org.nativescript.nativescriptapps/files/app/tns_modules/nativescript-oauth/tns-oauth-webview-helper.js', line: 40, column: 18
04-11 21:58:59.660 18848 18848 W System.err: 
04-11 21:58:59.660 18848 18848 W System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
04-11 21:58:59.660 18848 18848 W System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
04-11 21:58:59.660 18848 18848 W System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
04-11 21:58:59.660 18848 18848 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1047)
04-11 21:58:59.660 18848 18848 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1028)
04-11 21:58:59.660 18848 18848 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1018)
04-11 21:58:59.660 18848 18848 W System.err: 	at com.tns.gen.android.webkit.WebViewClient_frnal_ts_helpers_l58_c38__TnsOAuthWebViewHelper.shouldOverrideUrlLoading(android.webkit.WebViewClient.java)
```

The issue seems to be a [deprecated method](https://developer.android.com/reference/android/webkit/WebViewClient.html?hl=es#shouldOverrideUrlLoading(android.webkit.WebView,%20java.lang.String)), which has been removed eventually.

However, I'm rather unsure if changing the signature in [tns-oauth-webview-helper.android.ts#L34](https://github.com/alexziskind1/nativescript-oauth/blob/master/tns-oauth-webview-helper.android.ts#L34) from `string` to `android.webkit.WebResourceRequest` is the way to go. What do you think, @alexziskind1 ? I could create a PR if it's OK.

**Comment by alexziskind1** [comment]
Hi Witold,

What are you trying to login with?

Alex

On Apr 11, 2017, at 4:15 PM, Witold Czaplewski <notifications@github.com>
wrote:

Device: OnePlus 3T
Android: 7.1.1
nativescript-oauth: 1.3.0

04-11 21:58:59.659 18848 18848 W System.err: com.tns.NativeScriptException:
04-11 21:58:59.659 18848 18848 W System.err: Calling js method
shouldOverrideUrlLoading failed
04-11 21:58:59.659 18848 18848 W System.err:
04-11 21:58:59.659 18848 18848 W System.err: TypeError: Parameter
'url' must be a string, not object
04-11 21:58:59.659 18848 18848 W System.err: File:
"file:///data/data/org.nativescript.nativescriptapps/files/app/tns_modules/nativescript-oauth/node_modules/url/url.js,
line: 112, column: 4
04-11 21:58:59.659 18848 18848 W System.err:
04-11 21:58:59.659 18848 18848 W System.err: StackTrace:
04-11 21:58:59.659 18848 18848 W System.err: 	Frame:
function:'Url.parse',
file:'file:///data/data/org.nativescript.nativescriptapps/files/app/tns_modules/nativescript-oauth/node_modules/url/url.js',
line: 112, column: 11
04-11 21:58:59.659 18848 18848 W System.err: 	Frame:
function:'urlParse',
file:'file:///data/data/org.nativescript.nativescriptapps/files/app/tns_modules/nativescript-oauth/node_modules/url/url.js',
line: 106, column: 5
04-11 21:58:59.659 18848 18848 W System.err: 	Frame:
function:'checkCodeIntercept',
file:'file:///data/data/org.nativescript.nativescriptapps/files/app/tns_modules/nativescript-oauth/tns-oauth.js',
line: 81, column: 40
04-11 21:58:59.660 18848 18848 W System.err: 	Frame:
function:'TnsOAuthWebViewHelper.shouldOverrideUrlLoading',
file:'file:///data/data/org.nativescript.nativescriptapps/files/app/tns_modules/nativescript-oauth/tns-oauth-webview-helper.js',
line: 40, column: 18
04-11 21:58:59.660 18848 18848 W System.err:
04-11 21:58:59.660 18848 18848 W System.err: 	at
com.tns.Runtime.callJSMethodNative(Native Method)
04-11 21:58:59.660 18848 18848 W System.err: 	at
com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
04-11 21:58:59.660 18848 18848 W System.err: 	at
com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
04-11 21:58:59.660 18848 18848 W System.err: 	at
com.tns.Runtime.callJSMethod(Runtime.java:1047)
04-11 21:58:59.660 18848 18848 W System.err: 	at
com.tns.Runtime.callJSMethod(Runtime.java:1028)
04-11 21:58:59.660 18848 18848 W System.err: 	at
com.tns.Runtime.callJSMethod(Runtime.java:1018)
04-11 21:58:59.660 18848 18848 W System.err: 	at
com.tns.gen.android.webkit.WebViewClient_frnal_ts_helpers_l58_c38__TnsOAuthWebViewHelper.shouldOverrideUrlLoading(android.webkit.WebViewClient.java)

The issue seems to be a deprecated method
<https://developer.android.com/reference/android/webkit/WebViewClient.html?hl=es#shouldOverrideUrlLoading(android.webkit.WebView,%20java.lang.String)>,
which has been removed eventually.

However, I'm rather unsure if changing the signature in
tns-oauth-webview-helper.android.ts#L34
<https://github.com/alexziskind1/nativescript-oauth/blob/master/tns-oauth-webview-helper.android.ts#L34>
from string to android.webkit.WebResourceRequest is the way to go. What do
you think, @alexziskind1 <https://github.com/alexziskind1> ? I could create
a PR if it's OK.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/alexziskind1/nativescript-oauth/issues/35>, or mute the
thread

**Comment by witi83** [comment]
It was a Facebook login.

**Comment by alexziskind1** [comment]
Thanks for reporting this. The latest version handles the problem

**Comment by witi83** [comment]
I can confirm that version 1.6.0 fixes the problem. Thanks a lot!
